const fs = require('fs');

const rawData = `*For Airlines*
Air India Ltd.
Air India Express Ltd.
Alliance Air Aviation Ltd.
India One Air Private Limited
Ghodawat Enterprises Pvt. Ltd. (STAR AIR)
Interglobe Aviation Ltd. (Indigo)
Just Udo Aviation Pvt. Ltd. (FLY91)
Quikjet Cargo Airlines Pvt. Ltd.
SNV Aviation Pvt. Ltd. (Akasa Air)
Spice Jet Ltd.
Skyhop Aviation Private limited
Blue Dart Aviation Ltd.

*FOR FTO*
Academy of Carver Aviation Pvt. Ltd.
Alchemist Aviation Pvt. Ltd.
Ambitions Flying Club Pvt. Ltd.
Asia Pacific Flight Training Academy Ltd.
ARCA Global Aviation Private Limited
Avyanna Aviation Pvt. Ltd.
Aviation Connectivity and Infrastructure Developers Pvt. Ltd.
Banasthali Vidyapith Gliding & Flying Club
Bihar Flying Institute
Blue Ray Aviation Pvt. Ltd.
The Bombay Flying Club
Chetak Aviation (A unit of Sultan Education Society)
Chimes Aviation Academy
Dunes Aviation Academy (A unit of Ganpat Care Foundation)
Ekvi Air Training Organization Pvt. Ltd.
Falcon Aviation Academy
Flytech Aviation Academy
FSTC Flying School Pvt. Ltd.
Garg Aviations Ltd.
Govt. Aviation Training Institute
The Gujarat Flying Club
Govt. Flying Training School
Haryana Institute of Civil Aviation
Indian Flying Academy (A unit of Shaurya Flight Sim Pvt. Ltd.)
Indira Gandhi Rashtriya Uran Akademi
Jet Serve Aviation Pvt. Ltd.
Jharkhand Flying Institute
The Madhya Pradesh Flying Club Ltd.
Nagpur Flying Club
National Flying Training Institute Pvt. Ltd
Orient Flight Aviation Academy
Patiala Aviation Club
Pioneer Flying Academy Pvt. Ltd
Rajiv Gandhi Academy for Aviation Technology
Redbird Flight Training Academy Pvt. Ltd.
Sha- Shib Flying Academy
Skynex Aero Pvt. Ltd.
SVKM NMIMS Academy of Aviation
Telangana State Aviation Academy
Vision Flying Training Institute
Wings Aviation Pvt. Ltd.

*For non schedule operators*
Aerokalinga Aviation Pvt. Ltd.
Afcom Holdings Ltd.
Air Charters Services Pvt. Ltd.
Airports Authority of India Flight Inspection Unit
Aman Aviation & Aerospace Solutions Pvt. Ltd.
Aone Helicopters Private Limited
AR Airways Pvt. Ltd.
Aryan Aviation Pvt. Ltd.
Arrow Aircrafts Sales & Charters Pvt. Ltd.
Aviation Connectivity & Infrastructure Developers Pvt. Ltd. (Entry with aircraft details)
Bajaj Aviation Pvt. Ltd.
Baramati Agro Limited
Bativala M Bhagvati Flying Charters LLP
B.G. Shirke Construction Technology Pvt. Ltd.
Carewell Aviation India Pvt. Ltd.
Charlie Foxtrot Aviation Service Pvt. Ltd.
Avocet Aviation Pvt. Ltd.
Chipsan Aviation Pvt. Ltd.
Deccan Charters Pvt. Ltd.
Dhillon Aviation Pvt. Ltd.
Dunes Aviation Private Limited
E-Factor Adventure Tourism (P) Ltd.
EHA Aviation Pvt. Ltd.
Empire Aircraft Management Services Pvt. Ltd.
Falcon Aviation Services Pvt. Ltd.
EIH Ltd.
EMSOS Aviation Private Limited
Everdeliver Logistics Pvt. Ltd.
Fern Aviation India Pvt. Ltd.
Forum I Aviation Pvt. Ltd.
Fairwinds Aviation Pvt. Ltd.
Flaps Aviation Pvt. Ltd.
FLYSBS AVIATION LIMITED
Freedom Charter Services Pvt. Ltd.
Global Vectra Helicorp Limited
GMR Aviation Pvt. Ltd.
Ghodawat Enterprises Pvt. Ltd.
Golden Baritone Private Limited (JATAYU)
Golden Crane Aviation Pvt. Ltd.
GSEC Aviation Limited
Himalyaputra Aviation Ltd.
Himalayan Heli Services Ltd.
Heligo Charters Pvt. Limited
Heritage Aviation Pvt. Ltd.
Himanad Management Services Private Limited
HN Safal Aviation Pvt. Ltd.
Hyderabad Airlines Pvt. Ltd.
IIC Technologies Limited
Indocopters Pvt. Ltd.
Indo Pacific Aviation Pvt. Ltd.
India Flysafe Aviation Ltd.
Innxt Aviation Pvt. Ltd.
IRM Pvt. Ltd.
Jhankar Aviation Pvt. Ltd.
Jet Serve Aviation Pvt. Ltd.
Joyalukkas India Limited
Kainos Aviation Private Limited
Kairamya Aviation Pvt. Ltd.
Kakini Enterprises Pvt. Ltd.
Karnavati Aviation Pvt. Ltd.
KAN Aerofoil Private Limited
Kelachandra Logistics Pvt. Ltd.
Kestrel Aviation Pvt. Ltd.
Khazana Jewellery Pvt. Ltd.
Kingscraft Aviation Private Limited
Kyathi Climate Modification Consultants LLP
Lakeworkoffice Club Pvt. Ltd.
LCL Aviation Pvt. Ltd. (ECOJET)
LMCS Infra Holdings Pvt. Ltd.
L & T Aviation Services Pvt. Ltd.
MAB Aviation Pvt. Ltd.
Maharaja Aviation Pvt. Ltd.
Mahindra Airways Ltd.
Malhotra Helikopters Pvt. Ltd.
Mandke and Mandke Infrastructure Pvt. Ltd.
Media House DND Private Limited
Modifi Aviations Pvt. Ltd.
MSPL Ltd.
Mytri Aviation Pvt. Ltd.
Navdurga Aviation Pvt. Ltd.
NIBE AERONAUTICS LIMITED
Niraant Aviation Pvt. Ltd.
OSS Air Management Pvt. Ltd.
Pawan Hans Ltd.
PILGRIMAGE AVIATION PRIVATE LIMITED
Pioneer Flying Academy Pvt. Ltd.
Pinnacle Air Pvt. Ltd.
Poonawalla Aviation Pvt. Ltd.
Property Ventures (India) Pvt. Ltd.
Pradhaan Air Express Pvt. Ltd.
Rajas Aerosports and Adventures Private Limited (Air Safari)
RAJHANS INFRACON (INDIA) PRIVATE LIMITED
Raymond Ltd. (Aviation Division)
Redbird Airways Pvt. Ltd.
Redbird Flight Training Academy Private Limited
Reliance Transport & Travels Pvt. Ltd.
Reliance Commercial Dealers Ltd.
Rithwik Green Power and Aviation Pvt. Ltd.
RIVAAN TECHNOLOGIES PRIVATE LIMITED
RPS Aviation Pvt. Ltd.
RPSG Resources Pvt Ltd.
Saarthi Airways Pvt. Ltd.
Saffron Strokes Private Limited
Sai Construction Pvt. Ltd.
Sapphire Airlines Pvt. Ltd.
Simm Samm Airways Pvt. Ltd.
Shivan Aadithya Air Services Pvt. Ltd.
Shraddha Energy and Infraprojects Private Limited
Sky One Airways Pvt. Ltd.
Span Air pvt. Ltd.
Skyblue Aviation Services Pvt. Ltd.
SkyJets International Pvt. Ltd.
Smart Wings Aviation Pvt. Ltd.
Sparzana Aviation Pvt. Ltd.
SKB Infracons Pvt. Ltd.
Sobha Puravankara Aviation Pvt. Ltd.
Steamhouse India Ltd.
Suhan Aviation Pvt. Ltd.
Syandan Aviation Pvt. Ltd.
Sreeji Aviation Pvt. Ltd.
TAI Jets Private Limited
Taj Air Ltd.
Tara Aviation Services Pvt. Ltd.
Target Air Services Pvt. Ltd.
Thumby Aviation Pvt. Ltd.
Trans Bharat Aviation Pvt. Ltd.
Transworld Jets Pvt Ltd
United Helicharters Pvt. Ltd.
Universal Airways Pvt. Ltd.
Vijayanand Travels Private Limited
Vimaan Airlines Pvt. Ltd.
Ventura Airconnect Ltd.
VSR Ventures Pvt. Ltd.
Wings Aviation Pvt. Ltd.
Zest Aviation Pvt. Ltd.

*For AME Training institues*
ACADEMY OF AVIATION & ENGINEERING
AERONAUTICAL TRAINING INSTITUTE, U.P.
AEROSPACE RESEARCH & DEVELOPMENT CENTRE
ALPINE INSTITUTE OF AERONAUTICS
BHARAT INSTITUTE OF AERONAUTICS
ACADEMY OF CARVER AVIATION PRIVATE LIMITED
COLLEGE OF AERONAUTICAL ENGINEERING
FALCON INSTITUTE OF AIRCRAFT MAINTENANCE ENGINEERS
FLYTECH AVIATION ACADEMY
GMR AIR CARGO AND AEROSPACE ENGINEERING LTD.
HAL PRAVARA AVIATION INSTITUTE
HERITAGE AVIATION PVT. LTD
HINDUSTAN AEROSPACE AND ENGINEERING
HINDUSTAN AVIATION ACADEMY
HINDUSTAN INSTITUTE OF ENGINEERING TECHNOLOGY
HYDERABAD COLLEGE OF AVIATION TECHNOLOGY
INDIAN AEROSPACE & ENGINEERING
INDIAN INSTITUTE OF AIRCRAFT ENGINEERING
INDIRA GANDHI RASHTRIYA URAN AKADEMI
INDIRA INSTITUTE OF AIRCRAFT ENGINEERING
INDRAPRASTH INSTITUTE OF AERONAUTICS
INDOCOPTERS PRIVATE LIMITED
INSTITUTE OF AERONAUTICS & ENGINEERING
INSTITUTE OF AIRCRAFT MAINTENANCE ENGINEERING (Gorakhpur)
INSTITUTE OF AIRCRAFT MAINTENANCE ENGINEERING (Aurangabad)
SHA-SHIB FLYING ACADEMY
INTERNATIONAL AIRCRAFT SALES PVT. LTD.
IRM PRIVATE LIMITED
JAWAHARLAL AVIATION INSTITUTE
JRN INSTITUTE OF AVIATION TECHNOLOGY
MOUNT ZION COLLEGE OF AIRCRAFT MAINTENANCE ENGINEERING
NDC INSTITUTE OF AIRCRAFT MAINTENANCE ENGINEERING
NEHRU COLLEGE OF AERONAUTICS & APPLIED SCIENCES
PAWAN HANS HELICOPTER TRAINING INSTITUTE
PUNE INSTITUTE OF AVIATION TECHNOLOGY
PUNJAB AIRCRAFT MAINTENANCE ENGINEERING COLLEGE
RAJIV GANDHI AVIATION ACADEMY
REDWINGS AERO TECHNIQUE PVT LTD
REGIONAL INSTITUTE OF AVIATION
SCHOOL FOR AIRCRAFT MAINTENANCE ENGINEERING
SCHOOL OF AERONAUTICS (NEEMRANA)
SHASHIB AVIATION ACADEMY
SHA-SHIB AEROSPACE ENGINEERING
SILVEROAK COLLEGE OF AVIATION TECHNOLOGY
SKY COLLEGE OF AERONAUTICAL ENGINEERING
STAR AVIATION ACADEMY
TELANGANA STATE AVIATION ACADEMY
THAKUR INSTITUTE OF AVIATION TECHNOLOGY
THE BOMBAY FLYING CLUB AME TRAINING INSTITUTE
THE SOUTHERN COLLEGE OF ENGINEERING & TECHNOLOGY
UTKAL AEROSPACE & ENGINEERING
VINAYAKA MISSIONS AVIATION ACADEMY
VSM AEROSPACE AME TRAINING SCHOOL
WESTERN INDIA INSTITUTE OF AERONAUTICS PVT. LTD
WINGSSS COLLEGE OF AVIATION TECHNOLOGY

*For Aircrafts & Content MRO domestic*
ACADEMY OF CARVER AVIATION PVT.LTD.
AERO INTERIORS PVT. LTD
AEROSPACE RESEARCH & DEVELOPOMENT CENTRE
AEROTECHNICS MRO SERVICES PRIVATE LIMITED
AI ENGINEERING SERVICES LTD.
AIR 7 STAR (A UNIT OF INTERNATIONAL AIRCRAFT SALES PVT LTD)
AIR ALLEGIANCE A UNIT OF KOHINOOR EDUCATIONAL SERVICES PVT LTD
AIR CHARTER SERVICES (P) LTD.
AIR INDIA LIMITED
AIR WORKS INDIA ENGINEERING PVT LTD
AIR WORKS INDIA ENGINEERING PVT LTD COMMERCIAL MRO
AIRCRAFT TELECOMM MAINTENANCE AGENCY
AIRFLEET MANAGERS PRIVATE LIMITED
AIRGOD MRO SERVICE PVT LTD
AMAN AVIATION & AEROSPACE SOLUTIONS PVT.LTD
AMC TECHNOLOGY
AMT AVIATION PVT LTD
APCO INFRATECH PRIVATE LIMITED
AR AIRWAYS (P) LTD.
ARCA GLOBAL AVIATION PVT. LTD.
ARROW AVIATION SERVICES (P) LTD
ARYAN AVIATION PVT LTD
ASIAN GARMENTS
AUTOLOGIX PVT. LTD.
AUTOTRADE AVIATION PRIVATE LIMITED
AVIASAFE AVIATION SERVICES PVT LTD
AVIATION CONNECTIVITY AND INFRASTRUCTURE DEVELOPERS PVT LTD (AIR TAXI)
AVIATION WING, DEPTT. OF HOME, GOVT. OF JHARKHAND
AVITR OPERATIONS & MAINTENANCE LLP
AVYANNA AVIATION PRIVATE LIMITED
BHARAT AVIATION PRIVATE LIMITED
BHEL- GE GAS TURBINE SERVICES PVT LTD.
BIRD EXECUJET AIRPORT SERVICES PVT. LTD.
BLUE DART AVIATION LIMITED
BLUE RAY AVIATION PVT.LTD.
BORDER SECURITY FORCE, AIR WING
BRCC AVIATION SERVICES PRIVATE LIMITED
CAMPING RETREATS OF INDIA PVT LTD
CHANDRAVARAN AEROLOGISTIX PVT LTD
CHETAK AVIATION (A UNIT OF SULTAN EDUCATION SOCIETY)
CHIMES AVIATION PVT. LTD.
CHIPSAN AVIATION PVT LTD
CHRISVIC AVIATION PRIVATE LIMITED
CIVIL AVIATION DEPARTMENT, GOVERNMENT OF UTTAR PRADESH
COCHIN INTERNATIONAL AVIATION SERVICES LTD.
DECCAN CHARTERS PRIVATE LIMITED
DIRECTORATE OF AVIATION GOVERNMENT OF CHATTISGARH, RAIPUR
DIRECTORATE OF AVIATION, GOVT. OF MADHYA PRADESH
DIRECTORATE OF STATE CIVIL AVIATION, GOVT. OF UTTARAKHAND
DUNES AEROTECH PVT. LTD
E FACTOR ADVENTURE TOURISM (P) LTD.
EKVI AIR TRAINING ORGANISATION PRIVATE LIMITED
EPSILON AEROSPACE PRIVATE LIMITED
FALCON AVIATION ACADEMY
FLAPS AVIATION PRIVATE LIMITED
FLYWINGS SIMULATOR TRAINING CENTRE LIMITED
FSTC FLYING SCHOOL PVT LTD
GHODAWAT ENTERPRISES PVT LTD
GLOBAL KONNECT AVIATION SERVICES PRIVATE LIMITED
GLOBAL VECTRA HELICORP LTD.
GMR AIR CARGO AND AEROSPACE ENGINEERING LIMITED
GRETEL NETWORK OF AIRCRAFTS AND TURBINE ENGINES AVIATION PRIVATE LIMITED
GUJRAT FLYING CLUB
HAVEUS AEROTECH INDIA LTD.
HELICOPTER MRO DIVISION
HELIGO CHARTERS PVT.LTD.
HERITAGE AVIATION PVT. LIMITED
HIMALAYAN HELI SERVICES LIMITED
HINDUSTAN AERONAUTICS LIMITED
HINDUSTAN AERONAUTICS LIMITED AIRCRAFT DIVISION
HINDUSTAN AERONAUTICS LIMITED ENGINE DIVISION
HINDUSTAN AERONAUTICS LIMITED HELICOPTER DIVISION
HINDUSTAN AERONAUTICS LIMITED TAD KANPUR
HINDUSTAN AERONAUTICS LIMITED, AVIONICS DIVISION, KORWA
HINDUSTAN AERONAUTICS LTD ACCESSORIES DIVISION
HINDUSTAN AEROSPACE AND ENGINEERING (MRO) A UNIT OF KOHINOOR EDUCATIONAL SER.PVT.LTD.
HORIZON AEROSPACE (INDIA) PVT. LTD.
INDAMER AVIATION PVT.LTD.
INDAMER MJETS AIRPORT SERVICES PRIVATE LIMITED
INDAMER TECHNICS PRIVATE LIMITED
INDIAN METALS & FERRO ALLOYS LTD.
INDIAONE AIR PRIVATE LIMITED
INDO PACIFIC AVIATION PVT LTD
INDOCOPTERS PRIVATE LIMITED
INNOVATIVE AVIATION PRIVATE LIMITED
INSTITUTE OF MANAGEMENT & TECHNOLOGIES
INSTRULAB
INTERGLOBE AVIATION LTD. (INDIGO)
INTERNATIONAL AIRCRAFT SALES PVT.LTD.
IRM PRIVATE LIMITED
JET SERVE AVIATION PVT. LTD.
JHANKAR AVIATION PVT. LTD.
JHARKHAND FLYING INSTITUTE
JSS AVIATION ENGINEERING & MAINTENANCE PVT. LTD.
JUST UDO AVIATION PRIVATE LIMITED
KANAERO TECHNICS PVT LTD
KASSTECH AEROSPACE PRIVATE LIMITED
KESTREL AVIATION PVT.LTD.
KRIS AERO SERVICES PVT.LTD.
LIVEWEL AIRTEAM INDIA PVT LTD
MAGNUM AVIATION PVT LTD
MAHARAJA AVIATION PVT.LTD.
MANAH AEROSPACE AND ENGINEERING PVT LTD.
MAX AEROSPACE & AVIATION PRIVATE LIMITED
MAX MRO SERVICES PVT. LIMITED
MINERVA AVIATION SERVICES
NANO AVIATION INDIA PRIVATE LIMITED
NIEMLA
NSCB AVIATION(P) LTD.
ORIENT FLIGHT PVT LTD
ORISSA STEVEDORES LTD, BIJU PATTANAIK AIRPORT, BHUBANESWAR
OSS AIR MANAGEMENT PVT LTD
PAWAN HANS LIMITED
PAWAN INDUSTRIES
PIONEER FLYING ACADEMY PRIVATE LIMITED
PROMQT MRO PRIVATE LIMITED
RAJIV GANDHI AVIATION ACADEMY
RAYMOND LIMITED
REDBIRD AIRWAYS PVT LTD
REDBIRD FLIGHT TRAINING ACADEMY PRIVATE LIMITED
REDWINGS AEROTECHNIQUE PVT LTD
RIGHT CHOICE AVIATION PVT.LTD.
SA AIR WORKS INDIA PVT LTD
SADDLES INTERNATIONAL AUTOMOTIVE AND AVIATION INTERIORS PVT. LTD.
SHAURYA AERONAUTICS PVT. LTD.
SHAURYA FLIGHT SIM PVT LTD
SIMM SAMM AIRWAYS PVT.LTD.
SKY ONE AIRWAYS (P) LTD.
SKYBLUE AVIATION SERVICES PRIVATE LIMITED
SKYBASE MRO SERVICES PRIVATE LIMITED
SKYHAWK HELISOLUTIONS PRIVATE LIMITED
SKYJETS INTERNATIONAL PRIVATE LIMITED
SKYHOP AVIATION PRIVATE LIMITED
SKYNEX AERO PVT LTD
SMART WING
SNV AVIATION PRIVATE LIMITED
SPICEJET LTD
SPICEJET TECHNIC PVT LTD
TAJ AIR LIMITED
TANEJA AEROSPACE AND AVIATION LTD
TATA STEEL LTD
TENTACLE AEROLOGISTIX PVT. LTD.
THALES INDIA PRIVATE LIMITED
THE BOMBAY FLYING CLUB
THE TATA POWER COMPANY LIMITED
THRIVENI EARTHMOVERS P LTD
THUMBY AVIATION PVT.LTD.
TRANS BHARAT AVIATION (P) LTD
TRANSWORLD JETS PRIVATE LIMITED
TURBO AVIATION PRIVATE LIMITED
UNITED HELICHARTERS PVT.LTD.
UTKAL AEROSPACE AND ENGINEERING-MRO
UY AVIATION PVT LTD
VANDANA AIRCRAFT SERVICES PVT LTD
VARMAN AVIATION PVT LTD
VENTURA AIRCONNECT LIMITED
VERTEX AVATION PVT LTD
VERTICAL AEROSPACE PRIVATE LIMITED
VIKRAM AVIATION PRIVATE LIMITED
VISION FLYING TRAINING INSTITUTE
VOLGA OVERSEAS PRIVATE LIMITED
VSR VENTURES PVT. LIMITED
YATIH AIR SERVICES PVT. LTD.
ZEXUS AIR SERVICES PRIVATE LIMITED

*For Aircraft & Component MRO (Maintenance Repair & Overhaul)Foreign*
LUFTHANSA TECHNIK AG
KLM ENGINEERING & MAINTENANCE
TURKISH AIRLINES TECHNIC INC.
KUWAIT AIRWAYS
SIA ENGINEERING (USA) INC
SIA ENGINEERING (PHILIPPINES) CORPORATION
SIA ENGINEERING COMPANY LTD.
NATIONAL AVIATION GROUND SUPPORT (NAGS)
THAI AIRWAYS INTERNATIONAL PUBLIC COMPANY LIMITED
VIETJET AVIATION JOINT STOCK COMPANY
FLIGHTCHECK COMMERCIAL AVIATION SERVICES, LLC
JAL ENGINEERING CO. LTD.
QATAR AIRWAYS (QCSC)
AIRCRAFT MAINTENANCE & ENGINEERING CORPORATION BEIJING
FALCON AVIATION SERVICES LLC.
MTU MAINTENANCE ZHUHAI CO. LTD
GE CALEDONIAN (GE AVIATION SERVICES CALEDONIAN)
STORM AVIATION LIMITED
QSA AERONAUTICAL ENGINEERING SERVICES, MOROCCO
UNITED TECHNOLOGIES CORPORATION D/B/A PRATT & WHITNEY COLUMBUS ENGINE CENTER
DBA DELTA TECH OPS
BAHRAIN AIRPORT SERVICES (BAS)
VECTOR AEROSPACE AUSTRALIA PTY LTD
CHINA AIRCRAFT SERVICES LIMITED
AEROTEC INTERNATIONAL INC
HAMILTON SUNDSTRAND POLAND SP.ZO.O
KEYSTONE TURBINE SERVICES
ASIA PACIFIC AEROSPACE PTY. LTD
GE CELMA LTDA
MITSUBISHI HEAVY INDUSTRIES AERO ENGINES LTD.
IBERIA LINEAS AEREAS DE ESPANA, S.A. SPAIN
AEROMARITIME MEDITERRANEAN LTD
JSC URAL WORKS OF CIVIL AVIATION
MTU MAINTENANCE BERLIN-BRANDENBURG GMBH
ISLAND AVIATION SERVICES LIMITED
KOREAN AIRLINES CO., LTD.
GA TELESIS ENGINE SERVICES (GATES)
HESTON MRO PTY.LTD.
PRATT & WHITNEY HOLDINGS SAS, PRATT & WHITNEY AIR NEW ZEALAND SERVICES T/A CHRISTCHURCH ENGINE CENTRE
DUNCAN AVIATION
GENERAL ENTERPRISES B.V.
GOODRICH AEROSTRUCTURES SERVICE CENTER-ASIA PTE. LTD.
STANDARD AERO BUSINESS AVIATION SERVICES LLC
GENERAL ELECTRIC COMPANY
BOMBARDIER SERVICES (UK) LTD
AEROSPACE TURBINE SERVICES AND SOLUTIONS LLC TRADING AS "SANAD AEROTECH"
ABLE ENGINEERING & COMPONENT SERVICES INC
BOMBARDIER AEROSPACE SERVICES SINGAPORE PTE. LTD
H+S AVIATION LIMITED
EXECUJET MRO SERVICES MIDDLE EAST FZCO.
HELICOPTER TECHNICAL SERVICE COMPANY
BEDEK AVIATION GROUP, ISRAEL AEROSPACE INDUSTRIES LTD
GE ENGINE SERVICES MALAYSIA
JET AVIATION (ASIA PACIFIC) PTE LTD
GE AIRCRAFT ENGINE SERVICES LIMITED
IHI CORPORATION
CESSNA ZURICH CITATION SERVICE CENTER GMBH
JORDAN AIRCRAFT MAINTENANCE LIMITED – JORAMCO
PRATT & WHITNEY CANADA CORP. – ST HUBERT SERVICE CENTRE
ST AEROSPACE ENGINES PTE LTD.
SAFRAN HELICOPTER ENGINES ASIA PTE. LTD.
DASSAULT AVIATION BUSINESS SERVICES SA
VECTOR AEROSPACE ASIA PTE. LTD. (STANDARDAERO)
EAGLE SERVICES ASIA PTE. LTD.
SAFRAN AIRCRAFT ENGINE SERVICES MOROCCO
HONEYWELL INT. PHOENIX REPAIR AND OVERHAUL
ST ENGINEERING AEROSPACE SYSTEMS PTE LTD
DASSAULT AVIATION BUSINESS SERVICES SA
TURBINE AERO REPAIR LIMITED
REVIMA
SAFRAN HELICOPTER ENGINES ASIA PTE. LTD.
PRATT & WHITNEY
PT GARUDA MAINTENANCE FACILITY AERO ASIA TBK
SAFRAN AIRCRAFT ENGINE SERVICES BRUSSELS
SAFRAN HELICOPTER ENGINES INDUSTRIA E COMERCIO DO BRASIL LTDA.
SAFEAIR TECHNICAL SDN BHD
SAFRAN AIRCRAFT ENGINES
UNITED TECHNOLOGIES D.B.A PRATT & WHITNEY
MTU MAINTENANCE HANNOVER GMBH
LEARJET INC
SEPANG AIRCRAFT ENGINEERING SDN BHD
STANDARD AERO (ALLIANCE) INC.
DASSAULT FALCON SERVICE
OMAN AIR (SOAC)
SRILANKAN AIRLINES LIMITED
PRATT & WHITNEY LINE MAINTENANCE SERVICES
DRAYTON AEROSPACE (XIAMEN) LANDING SYSTEMS LTD.
GLOBAL JET TECHNIC
HARRODS AVIATION LIMITED
GULFSTREAM SERVICES CORPORATION
PRATT & WHITNEY THY TEKNIK UCAK MOTORU MERKEZI, LTD. SIRKETI
AIR CANADA
STANDARD AERO (SAN ANTONIO), INC. DBA STANDARDAERO
BOMBARDIER AEROSPACE (DUBAI) DWC-LLC
SOUTHEAST ASIA AIRCRAFT MAINTENANCE SERVICES CO. LTD.
AUSTRIAN AIRLINES AG
NAYAK-LM GMBH
GE ON WING SUPPORT KOREA INC.
ACC COLUMBIA JET SERVE GMBH
AERO NORWAY AS.
ASIA AEROTECHNIC SDN BHD
BELL TEXTRON ASIA (PTE.) LTD.
REVIMA ASIA PACIFIC LTD.
BOS AEROSPACE LIMITED
WILLIAMS INTERNATIONAL CO LLC
SOUTHERN AIRPORTS AIRCRAFT MAINTENANCE SERVICES
ATHENS AEROSERVICES AE
SILKWAY TECHNICS
UAB FL TECHNICS
CRYSTAL AERO SOLUTIONS
PHOENIX RISING AVIATION INC.
PT.JAS AERO ENGINEERING SERVICES
DRAYTON AEROSPACE SA
SOCIETE AIR FRANCE
GLOBAL AEROSPACE CORPORATION
ATITECH S.P.A.
THE BOEING COMPANY
TRANSPORTES AEREOS PORTUGUESES, S.A.
MACH TECHNIK AIRCRAFT MAINTENANCE
GULFSTREAM AEROSPACE, LTD
TURBINE ENGINE SPECIALIST INC.
NATIONAL AVIATION SERVICES W.L.L
EPCOR BV
SR TECHNICS LINE MAINTENANCE AG
HAECO COMPOSITE STRUCTURES (JINJIANG) CO., LTD
GROUND2AIR LTD
PT BATAM TEKNIK
VORTEX AVIATION IRELAND LTD.
SIA JET FLIGHT SERVICE
POS AVIATION ENGINEERING SERVICES SDN. BHD.
KASE AVIATION CO., LTD
AIR ASTANA JSC
JET AVIATION DUBAI LLC
OGMA - INDUSTRIA AERONAUTICA DE PORTUGAL S.A.
PREMIER AIR CENTRE LLC, DBA WEST STAR AVIATION LLC
STANDARDAERO FRANCE S.A.S.
EVERGREEN AVIATION TECHNOLOGIES CORP
ETIHAD AIRWAYS ENGINEERING L.L.C.
ST ENGINEERING AEROSPACE SERVICES COMPANY PTE. LTD.
MODULAR AVIATION SERVICES
SR TECHNICS SWITZERLAND LTD
ASIA DIGITAL ENGINEERING SDN BHD
HONG KONG AERO ENGINE SERVICES LIMITED (HAESL)
DISCOVERY MAINTENANCE LLC
TMX AERO, LLC
AVIATION PARTNERSHIP (PHIL) CORP
SAFRAN LANDING SYSTEMS SERVICES SINGAPORE PTE. LTD.
BOSA-THAYAAN AIRCRAFT SERVICE CO.,LTD.
RBIH MIDDLE EAST FZE
LIEBHERR-AEROSPACE LINDENBERG GMBH
PRIME TURBINE, LLC. DBA PRIME TURBINES
JET AVIATION AG
MERCURY AIR TECHNIC PVT. LTD.
AIR SEYCHELLES LTD
BE AERO HAVACILIK A.S.
PRATT & WHITNEY CANADA (SEA) PTE LTD
ABS JETS, A.S.
MACH II MAINTENANCE CORP

*For List of technical writing organizations*
1. TWB – Technical Writing & Business Solutions
2. Wissen Glanz India Pvt. Ltd.
3. Dautya Aerospace Pvt. Ltd.
4. Aerotics Technologies LLP
5. Nova Global
6. DELOS Consulting Pvt. Ltd.
7. Nebo Technical Service Pvt. Ltd.
8. Wipro – Aerospace Technical Publications
9. Safran Engineering Services India
10. Brick and Byte
11. Buckeye Overseas Pvt. Ltd.
12. SPI Aviation
13. Collins Aerospace India
14. Cyient
15. Tata Technologies
16. Quest Global India
17. Alten India
18. Belcan India
19. HCLTech – Aerospace & Engineering Services
20. Capgemini Engineering India
21. Akkodis India
22. L&T Technology Services (LTTS)
23. Tech Mahindra – Aerospace & Engineering Services
24. Tata Elxsi
25. Infosys – Engineering Services
26. TCS – Engineering & Industrial Services
27. AXISCADES Technologies
28. KPIT Technologies
29. Cyient DLM / Cyient Aerospace
30. Expleo India

Aircraft Components Manufacturers:
1. Hindustan Aeronautics Limited (HAL)
2. Tata Advanced Systems Limited (TASL)
3. Dynamatic Technologies
4. Aequs Aerospace
5. Mahindra Aerospace
6. Alpha Tocol Engineering Services
7. Rossell Techsys
8. Taneja Aerospace & Aviation
9. JJG Aero
10. L&T Precision Engineering
11. Safran Aircraft Engines India
12. MTU Aero Engines India
13. Godrej Aerospace
14. Azad Engineering
15. Wipro Infrastructure Engineering
16. Safran Landing Systems India
17. Collins Aerospace India
18. Cyient
19. Data Patterns
20. Kineco Aerospace
21. Sundram Fasteners
22. Unbrako India
23. Bharat Forge
24. Rolls-Royce India
25. GE Aerospace India
26. Spirit AeroSystems India
27. Adani Defence & Aerospace

Aircraft Manufactures:
1. Airbus India
2. Boeing India
3. Dassault Aviation India
4. Embraer India 
5. HAL (Hindustan Aeronautics Limited
6. Mahindra Aerospace
7. Taneja Aerospace & Aviation`;

const lines = rawData.split('\n');
let currentSection = null;
const parsedData = {};

lines.forEach(line => {
  line = line.trim();
  if (!line) return;

  const headerMatch = line.match(/^\*?For\s+(.*?)\*?$/i) || line.match(/^(Aircraft Components Manufacturers|Aircraft Manufactures):$/i);
  if (headerMatch) {
    let name = headerMatch[1].replace(/\*$/, '').trim();
    if (name === 'List of technical writing organizations') name = 'Technical Writing Organizations';
    if (name === 'Aircrafts & Content MRO domestic' || name === 'Aircraft & Component MRO (Maintenance Repair & Overhaul) Domestic') name = 'Aircraft & Component MRO Domestic';
    if (name === 'Aircraft & Component MRO (Maintenance Repair & Overhaul)Foreign') name = 'Aircraft & Component MRO Foreign';
    if (name === 'non schedule operators') name = 'Non Schedule Operators';
    if (name === 'AME Training institues') name = 'AME Training Institutes';
    
    currentSection = name;
    parsedData[currentSection] = [];
  } else {
    if (currentSection) {
      // Remove leading numbers for some lists
      line = line.replace(/^\d+\.\s*/, '');
      parsedData[currentSection].push(line);
    }
  }
});

// Build the JS object string
let objContent = 'const jobData = {\n';
for (const [key, items] of Object.entries(parsedData)) {
  let listHtml = '<div class="p-4 bg-white border border-gray-100 rounded-xl shadow-sm h-full">\n<ul class="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm md:text-base text-gray-700">\n';
  items.forEach(item => {
    listHtml += '  <li class="flex items-start"><i class="fas fa-plane text-[#ff4301] mt-1 mr-3 flex-shrink-0 text-sm"></i><span class="leading-tight">' + item.replace(/'/g, "&#39;") + '</span></li>\n';
  });
  listHtml += '</ul>\n</div>';
  
  objContent += '            "' + key + '": `' + listHtml + '`,\n';
}
objContent += '          };';

const files = [
  '../frontend/Pages/ame-b1-1.html',
  '../frontend/Pages/ame-b1-2.html'
];

files.forEach(file => {
  let html = fs.readFileSync(file, 'utf8');
  
  // Regex to replace the jobData object block
  const regex = /const jobData = \{[\s\S]*?\};/;
  
  if (regex.test(html)) {
    html = html.replace(regex, objContent);
    fs.writeFileSync(file, html);
    console.log('Injected data into ' + file);
  } else {
    console.log('Could not find jobData in ' + file);
  }
});
